# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mapreduce_pb2 as mapreduce__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mapreduce_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MapReduceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapTask = channel.unary_unary(
                '/MapReduceService/MapTask',
                request_serializer=mapreduce__pb2.MapRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.MapResponse.FromString,
                _registered_method=True)
        self.ReduceTask = channel.unary_unary(
                '/MapReduceService/ReduceTask',
                request_serializer=mapreduce__pb2.ReduceRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.ReduceResponse.FromString,
                _registered_method=True)


class MapReduceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MapTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReduceTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapReduceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapTask': grpc.unary_unary_rpc_method_handler(
                    servicer.MapTask,
                    request_deserializer=mapreduce__pb2.MapRequest.FromString,
                    response_serializer=mapreduce__pb2.MapResponse.SerializeToString,
            ),
            'ReduceTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceTask,
                    request_deserializer=mapreduce__pb2.ReduceRequest.FromString,
                    response_serializer=mapreduce__pb2.ReduceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MapReduceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MapReduceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MapReduceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MapTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MapReduceService/MapTask',
            mapreduce__pb2.MapRequest.SerializeToString,
            mapreduce__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReduceTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MapReduceService/ReduceTask',
            mapreduce__pb2.ReduceRequest.SerializeToString,
            mapreduce__pb2.ReduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
