# workers.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mr-worker1-deployment # Deployment for worker 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-worker1
  template:
    metadata:
      labels:
        app: mr-worker1
    spec:
      containers:
      - name: worker
        image: wordcount-mapreduce-worker # The image you built in Step 1
        imagePullPolicy: IfNotPresent     # Tells K8s to use the local image
        ports:
        - containerPort: 50051
        env:
        - name: WORKER_ID
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: worker1 # This name MUST match what your client.py expects
spec:
  selector:
    app: mr-worker1 # This links the Service to the Deployment above
  ports:
    - protocol: TCP
      port: 50051      # The port the client calls
      targetPort: 50051 # The port on the pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mr-worker2-deployment # Deployment for worker 2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-worker2
  template:
    metadata:
      labels:
        app: mr-worker2
    spec:
      containers:
      - name: worker
        image: wordcount-mapreduce-worker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: WORKER_ID
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: worker2 # This name MUST match what your client.py expects
spec:
  selector:
    app: mr-worker2
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mr-worker3-deployment # Deployment for worker 3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-worker3
  template:
    metadata:
      labels:
        app: mr-worker3
    spec:
      containers:
      - name: worker
        image: wordcount-mapreduce-worker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: WORKER_ID
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: worker3 # This name MUST match what your client.py expects
spec:
  selector:
    app: mr-worker3
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mr-worker4-deployment # Deployment for worker 4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-worker4
  template:
    metadata:
      labels:
        app: mr-worker4
    spec:
      containers:
      - name: worker
        image: wordcount-mapreduce-worker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: WORKER_ID
          value: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: worker4 # This name MUST match what your client.py expects
spec:
  selector:
    app: mr-worker4
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mr-worker5-deployment # Deployment for worker 5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-worker5
  template:
    metadata:
      labels:
        app: mr-worker5
    spec:
      containers:
      - name: worker
        image: wordcount-mapreduce-worker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: WORKER_ID
          value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: worker5 # This name MUST match what your client.py expects
spec:
  selector:
    app: mr-worker5
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mr-worker6-deployment # Deployment for worker 6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr-worker6
  template:
    metadata:
      labels:
        app: mr-worker6
    spec:
      containers:
      - name: worker
        image: wordcount-mapreduce-worker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
        env:
        - name: WORKER_ID
          value: "6"
---
apiVersion: v1
kind: Service
metadata:
  name: worker6 # This name MUST match what your client.py expects
spec:
  selector:
    app: mr-worker6
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051